version: "3"

services:
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: 127.0.0.1
            PMA_PORT: 3306
            APACHE_PORT: 8080
            UPLOAD_LIMIT: 1G
        restart: unless-stopped
        network_mode: host
        ports:
            - 8080:8080
